# 站点信息
title: 我的极简博客
description: 一个极简的Jekyll博客
baseurl: "/d1"  # 关键：子仓库的路径前缀，如 "/blog" 或 "/myrepo"
url: "https://pcrock99.github.io"  # 你的GitHub Pages主域名
## 头像地址
avatar: https://z3.ax1x.com/2021/04/26/gSVHXQ.gif

# 主题
remote_theme: pages-themes/hacker@v0.2.0

# 路径配置
permalink: /:year/:month/:day/:title/
paginate: 5
paginate_path: "/page:num/"

# 插件
plugins:
  - jekyll-paginate
  - jekyll-remote-theme      # 激活远程主题插件
