title: 我的极简博客
description: 一个极简的Jekyll博客
baseurl: "/d1"  # 如果是子仓库，改成 "/仓库名"
url: ""      # 留空即可  

# 使用GitHub Pages自带主题
theme: jekyll-theme-hacker

# 分页配置
paginate: 5
paginate_path: "/page:num/"

# 插件
plugins:
  - jekyll-paginate

permalink: /:year/:month/:day/:title/
